// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCELUz2FR0lcluy0JmLg6xIGKE3NPDun58',
    appId: '1:242479385211:web:83f43e45a2e71c97a9f0de',
    messagingSenderId: '242479385211',
    projectId: 'sample-firebase-ai-app-4d939',
    authDomain: 'sample-firebase-ai-app-4d939.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-4d939.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjhlblhGZWKlux9pLV8xKeaXLPxUJt-wM',
    appId: '1:242479385211:android:95b2da87fb4fe0caa9f0de',
    messagingSenderId: '242479385211',
    projectId: 'sample-firebase-ai-app-4d939',
    storageBucket: 'sample-firebase-ai-app-4d939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6no4qVE5lmg9z7rkZSVsqcw2MOh48BiA',
    appId: '1:242479385211:ios:34d484991a2efcb6a9f0de',
    messagingSenderId: '242479385211',
    projectId: 'sample-firebase-ai-app-4d939',
    storageBucket: 'sample-firebase-ai-app-4d939.firebasestorage.app',
    iosBundleId: 'com.example.trashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6no4qVE5lmg9z7rkZSVsqcw2MOh48BiA',
    appId: '1:242479385211:ios:34d484991a2efcb6a9f0de',
    messagingSenderId: '242479385211',
    projectId: 'sample-firebase-ai-app-4d939',
    storageBucket: 'sample-firebase-ai-app-4d939.firebasestorage.app',
    iosBundleId: 'com.example.trashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCELUz2FR0lcluy0JmLg6xIGKE3NPDun58',
    appId: '1:242479385211:web:63da8f538f7941c3a9f0de',
    messagingSenderId: '242479385211',
    projectId: 'sample-firebase-ai-app-4d939',
    authDomain: 'sample-firebase-ai-app-4d939.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-4d939.firebasestorage.app',
  );
}
